import prisma from "@/lib/db/prisma";
import {
  ActivityType,
  AutomationStatus,
  ConversationChannel,
  LeadStatus,
  ReplyClassification,
} from "@prisma/client";
import { NotFoundError } from "@/lib/api/response";
import { aiComplete, parseAIJson } from "@/lib/ai/provider";
import { buildReplyAnalysisPrompt } from "@/lib/ai/prompts";
import { activityService } from "@/services/activity.service";
import { aiOutreachService } from "@/services/ai-outreach.service";

interface ReplyAnalysis {
  classification: string;
  sentiment: string;
  summary: string;
  suggestedResponse: string;
  shouldAutoSend: boolean;
  recommendedLeadStatus: string;
  nextAction: string;
}

export class ConversationService {
  async list(filters?: { leadId?: string; channel?: ConversationChannel }) {
    return prisma.conversation.findMany({
      where: {
        ...(filters?.leadId ? { leadId: filters.leadId } : {}),
        ...(filters?.channel ? { channel: filters.channel } : {}),
      },
      include: {
        lead: {
          select: {
            id: true,
            fullName: true,
            companyName: true,
            email: true,
            status: true,
            automationStatus: true,
          },
        },
      },
      orderBy: { createdAt: "desc" },
      take: 100,
    });
  }

  async processInboundReply(params: {
    leadId: string;
    channel: ConversationChannel;
    content: string;
    subject?: string;
    userId?: string;
    autoRespond?: boolean;
  }) {
    const lead = await prisma.lead.findFirst({
      where: { id: params.leadId, deletedAt: null },
    });
    if (!lead) throw new NotFoundError("Lead not found");

    await prisma.lead.update({
      where: { id: params.leadId },
      data: { automationStatus: AutomationStatus.PROCESSING_REPLY },
    });

    const inbound = await prisma.conversation.create({
      data: {
        leadId: params.leadId,
        channel: params.channel,
        subject: params.subject,
        content: params.content,
        isInbound: true,
      },
    });

    const history = await prisma.conversation.findMany({
      where: { leadId: params.leadId },
      orderBy: { createdAt: "asc" },
      take: 20,
    });

    const historyText = history
      .map((c) => `[${c.isInbound ? "THEM" : "US"}] ${c.content}`)
      .join("\n");

    const result = await aiComplete({
      feature: "reply_analysis",
      userId: params.userId,
      jsonMode: true,
      temperature: 0.4,
      messages: [
        {
          role: "system",
          content: "You are a B2B sales assistant. Analyze replies and suggest responses. JSON only.",
        },
        {
          role: "user",
          content: buildReplyAnalysisPrompt(lead, historyText, params.content),
        },
      ],
    });

    const analysis = parseAIJson<ReplyAnalysis>(result.content);
    const classification = this.mapClassification(analysis.classification);
    const leadStatus = this.mapLeadStatus(analysis.recommendedLeadStatus);

    await prisma.conversation.update({
      where: { id: inbound.id },
      data: {
        classification,
        aiAnalysis: analysis as object,
        summary: analysis.summary,
      },
    });

    await prisma.lead.update({
      where: { id: params.leadId },
      data: { status: leadStatus },
    });

    await activityService.log({
      leadId: params.leadId,
      userId: params.userId,
      type: ActivityType.REPLY_ANALYZED,
      title: `Reply classified: ${classification}`,
      description: analysis.summary,
    });

    let responseConversation = null;

    if (params.autoRespond !== false && lead.autoReplyEnabled && analysis.suggestedResponse) {
      responseConversation = await prisma.conversation.create({
        data: {
          leadId: params.leadId,
          channel: params.channel,
          content: analysis.suggestedResponse,
          isInbound: false,
          metadata: {
            autoGenerated: true,
            status: analysis.shouldAutoSend ? "sent" : "draft",
          },
        },
      });

      if (analysis.shouldAutoSend && params.channel === ConversationChannel.EMAIL && lead.email) {
        await aiOutreachService.sendOutreach(
          params.leadId,
          responseConversation.id,
          params.userId
        );
      }
    }

    await prisma.lead.update({
      where: { id: params.leadId },
      data: {
        automationStatus:
          analysis.classification === "INTERESTED" ||
          analysis.classification === "MEETING_REQUEST"
            ? AutomationStatus.COMPLETED
            : AutomationStatus.AWAITING_REPLY,
      },
    });

    return { inbound, analysis, response: responseConversation };
  }

  private mapClassification(c: string): ReplyClassification {
    const map: Record<string, ReplyClassification> = {
      INTERESTED: ReplyClassification.INTERESTED,
      NOT_INTERESTED: ReplyClassification.NOT_INTERESTED,
      ASK_LATER: ReplyClassification.ASK_LATER,
      NEED_INFORMATION: ReplyClassification.NEED_INFORMATION,
      PRICE_QUESTION: ReplyClassification.PRICE_QUESTION,
      MEETING_REQUEST: ReplyClassification.MEETING_REQUEST,
      PROPOSAL_REQUEST: ReplyClassification.PROPOSAL_REQUEST,
      OTHER: ReplyClassification.OTHER,
    };
    return map[c] ?? ReplyClassification.OTHER;
  }

  private mapLeadStatus(s: string): LeadStatus {
    const map: Record<string, LeadStatus> = {
      REPLIED: LeadStatus.REPLIED,
      INTERESTED: LeadStatus.INTERESTED,
      MEETING: LeadStatus.MEETING,
      LOST: LeadStatus.LOST,
      QUALIFIED: LeadStatus.QUALIFIED,
    };
    return map[s] ?? LeadStatus.REPLIED;
  }
}

export const conversationService = new ConversationService();
