/** Feature keys enforced server-side against plan_features.limit_value */
export const FEATURE_KEYS = {
  USERS: "users",
  OPPORTUNITIES: "opportunities",
  AI_CALLS: "ai_calls",
  EMAILS: "emails",
  SEQUENCES: "sequences",
  SOURCES: "sources",
  ENRICHMENT: "enrichment",
  INBOX_ACCOUNTS: "inbox_accounts",
  AUTOMATION: "automation",
  ADVANCED_AI: "advanced_ai",
  LEARNING: "learning",
  CONNECTORS: "connectors",
} as const;

export type FeatureKey = (typeof FEATURE_KEYS)[keyof typeof FEATURE_KEYS];

export const DEFAULT_PLANS = [
  {
    name: "Free",
    description: "Get started with core opportunity and outreach tools",
    price: 0,
    currency: "USD",
    billingInterval: "MONTHLY" as const,
    isDefault: true,
    sortOrder: 0,
    features: [
      { featureKey: FEATURE_KEYS.USERS, limitValue: 2, enabled: true },
      { featureKey: FEATURE_KEYS.OPPORTUNITIES, limitValue: 50, enabled: true },
      { featureKey: FEATURE_KEYS.AI_CALLS, limitValue: 100, enabled: true },
      { featureKey: FEATURE_KEYS.EMAILS, limitValue: 100, enabled: true },
      { featureKey: FEATURE_KEYS.SEQUENCES, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.SOURCES, limitValue: 2, enabled: true },
      { featureKey: FEATURE_KEYS.ENRICHMENT, limitValue: 25, enabled: true },
      { featureKey: FEATURE_KEYS.INBOX_ACCOUNTS, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.AUTOMATION, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.ADVANCED_AI, limitValue: 0, enabled: false },
      { featureKey: FEATURE_KEYS.LEARNING, limitValue: 0, enabled: false },
      { featureKey: FEATURE_KEYS.CONNECTORS, limitValue: 2, enabled: true },
    ],
  },
  {
    name: "Growth",
    description: "For growing sales teams running multi-source pipeline",
    price: 99,
    currency: "USD",
    billingInterval: "MONTHLY" as const,
    isDefault: false,
    sortOrder: 1,
    features: [
      { featureKey: FEATURE_KEYS.USERS, limitValue: 10, enabled: true },
      { featureKey: FEATURE_KEYS.OPPORTUNITIES, limitValue: 1000, enabled: true },
      { featureKey: FEATURE_KEYS.AI_CALLS, limitValue: 2000, enabled: true },
      { featureKey: FEATURE_KEYS.EMAILS, limitValue: 5000, enabled: true },
      { featureKey: FEATURE_KEYS.SEQUENCES, limitValue: 20, enabled: true },
      { featureKey: FEATURE_KEYS.SOURCES, limitValue: 10, enabled: true },
      { featureKey: FEATURE_KEYS.ENRICHMENT, limitValue: 1000, enabled: true },
      { featureKey: FEATURE_KEYS.INBOX_ACCOUNTS, limitValue: 5, enabled: true },
      { featureKey: FEATURE_KEYS.AUTOMATION, limitValue: 10, enabled: true },
      { featureKey: FEATURE_KEYS.ADVANCED_AI, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.LEARNING, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.CONNECTORS, limitValue: 10, enabled: true },
    ],
  },
  {
    name: "Scale",
    description: "Unlimited-leaning entitlements for revenue teams",
    price: 299,
    currency: "USD",
    billingInterval: "MONTHLY" as const,
    isDefault: false,
    sortOrder: 2,
    features: [
      { featureKey: FEATURE_KEYS.USERS, limitValue: 50, enabled: true },
      { featureKey: FEATURE_KEYS.OPPORTUNITIES, limitValue: 10000, enabled: true },
      { featureKey: FEATURE_KEYS.AI_CALLS, limitValue: 20000, enabled: true },
      { featureKey: FEATURE_KEYS.EMAILS, limitValue: 50000, enabled: true },
      { featureKey: FEATURE_KEYS.SEQUENCES, limitValue: 100, enabled: true },
      { featureKey: FEATURE_KEYS.SOURCES, limitValue: 50, enabled: true },
      { featureKey: FEATURE_KEYS.ENRICHMENT, limitValue: 10000, enabled: true },
      { featureKey: FEATURE_KEYS.INBOX_ACCOUNTS, limitValue: 25, enabled: true },
      { featureKey: FEATURE_KEYS.AUTOMATION, limitValue: 100, enabled: true },
      { featureKey: FEATURE_KEYS.ADVANCED_AI, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.LEARNING, limitValue: 1, enabled: true },
      { featureKey: FEATURE_KEYS.CONNECTORS, limitValue: 50, enabled: true },
    ],
  },
] as const;
